packages:
  - apps/*
  - libs/*
  - dbs/*

onlyBuiltDependencies:
  - '@beezone/sample-db'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - nx
  - prisma
