export const PUBLIC_ACCESS_METADATA_KEY = 'PUBLIC_ACCESS_METADATA_KEY';
export const RESOURCE_NAME_METADATA_KEY = 'RESOURCE_NAME_METADATA_KEY';
export const OPERATION_NAME_METADATA_KEY = 'OPERATION_NAME_METADATA_KEY';
