export enum Operations {
  READ_ONE = 'READ_ONE',
  WRITE_ONE = 'WRITE_ONE',
  UDPATE_ONE = 'UDPATE_ONE',
  DELETE_ONE = 'DELETE_ONE',

  READ_MANY = 'READ_MANY',
  WRITE_MANY = 'WRITE_MANY',
  UDPATE_MANY = 'UDPATE_MANY',
  DELETE_MANY = 'DELETE_MANY',

  READ_ONE_OWN = 'READ_ONE_OWN',
  WRITE_ONE_OWN = 'WRITE_ONE_OWN',
  UDPATE_ONE_OWN = 'UDPATE_ONE_OWN',
  DELETE_ONE_OWN = 'DELETE_ONE_OWN',

  READ_MANY_OWN = 'READ_MANY_OWN',
  WRITE_MANY_OWN = 'WRITE_MANY_OWN',
  UDPATE_MANY_OWN = 'UDPATE_MANY_OWN',
  DELETE_MANY_OWN = 'DELETE_MANY_OWN',
}
