// @index(['./**/*.ts', '!./**/*.{spec,test}.ts'], f => `export * from '${f.path}.js'`)
export * from './lib/property/array-property.js'
export * from './lib/property/boolean-property.js'
export * from './lib/property/common-number-property.js'
export * from './lib/property/common-property.js'
export * from './lib/property/integer-property.js'
export * from './lib/property/number-property.js'
export * from './lib/property/object-property.js'
export * from './lib/property/property.js'
export * from './lib/property/string-property.js'
export * from './lib/special/some-boolean-property.js'
export * from './lib/special/some-object-property.js'
export * from './lib/transformer/default-value-transformer.js'
export * from './lib/transformer/json-transformer.js'
export * from './lib/transformer/trim-transformer.js'
